app/models.py
from . import db
from flask_login import UserMixin
from datetime import datetime

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    password_hash = db.Column(db.String(200), nullable=False)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    club = db.Column(db.String(100), nullable=True)
    
    def full_name(self):
        return self.first_name + ' ' + self.last_name

    def __repr__(self):
        return '<User %r>' % self.username

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.String(200), nullable=False)
    club = db.Column(db.String(200), nullable=True)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    user = db.relationship('User', backref=db.backref('posts', lazy=True))

    def __repr__(self):
        return '<Post %r>' % self.id

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import Config

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = '/login' # Specifying the login view


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    login_manager.init_app(app)

    from app.models import User

    # User loader func
    @login_manager.user_loader
    def load_user(user_id):
        return db.session.get((User), int(user_id))

    from .routes import bp as routes_bp
    app.register_blueprint(routes_bp)

    from .auth import auth_bp
    app.register_blueprint(auth_bp)

    from .user import user_bp
    app.register_blueprint(user_bp)

    from .post import post_bp
    app.register_blueprint(post_bp)

    return app



    

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from . import db
from .models import User, Post
from flask_login import login_manager, login_user, current_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash


auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        first_name = request.form['firstname']
        last_name = request.form['lastname']

        hashed_password = generate_password_hash(password)
        new_user = User(username=username, 
                        password_hash=hashed_password, 
                        email=email, 
                        first_name=first_name,
                        last_name=last_name)

        try:
            db.session.add(new_user)
            db.session.commit()
            return redirect('/')
        except:
            return 'Failed to register user'
        
    return render_template('register.html', user=current_user, include_header=True)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()

        
        if user and check_password_hash(user.password_hash, password):
            login_user(user)
            return redirect('/')
        else:
            flash('Login failed. Check your username and password.')
    
    return render_template('login.html', user=current_user, include_header=True)

@auth_bp.route('/logout')
def logout():
    logout_user()
    return redirect('/')

app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from . import db
from .models import User, Post
from flask_login import current_user, login_required

bp = Blueprint('main', __name__)

@bp.route('/', methods=['GET', 'POST'])
def index():
    posts = Post.query.order_by(Post.date_created).all()
    users = User.query.order_by(User.id).all()
    return render_template('index.html', posts=posts, user=current_user, include_header=True)

app/templates/base.html
<!DOCTYPE html>
<html lang="en"> 
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
    <link rel="stylesheet" href="{{url_for('static',filename='dist/css/output.css')}}">
    <script src="https://kit.fontawesome.com/73a2fe9eaa.js" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% if include_header %} 
      {% include 'header.html' %} 
    {% endif %} 
  
    {% block body %}
    {% endblock %}
    
  </body>
</html>

app/templates/header.html
{% block header %}
<!-- Top Header --> 
<header class="site-header flex 
              justify-between 
              bg-csun-red 
            text-white w-full
              py-4
              px-6
              text-lg">

  <!-- Logo maybe --> 
  <div class="title text-2xl"><a href="/">OnlyClubs</a></div>

  <!-- Navbar --> 
  <nav class="flex-no-wrap relative flex w-full justify-end items-center" >
    <ul class="flex gap-6 flex-col md:flex-row">
      <!-- Menu items --> 
      <li class="transition-all duration-300 ease-out hover:opacity-85"><a href="#events">UPCOMING EVENTS</a></li>
      <li class="transition-all duration-300 ease-out hover:opacity-85"><a href="/new-post">POST EVENT</a></li>
      
      <!-- If user authed, show account icon fa-user --> 
      {% if user.is_authenticated %}
      <li class=" group transition-all">
        <a href="#account"  class="transition-all duration-300 ease-out hover:opacity-85">
          <i class="fa-solid fa-user"></i>
        </a>
        <ul class="absolute invisible group-hover:visible group-hover:opacity-100 
        opacity-0 transform scale-95 group-hover:scale-100 transition-all duration-800 ease-out 
        top-full mt-1 -right-2 p-2 bg-white text-center text-gray-900 shadow-md whitespace-nowrap">
          <!-- Drop-down menu options --> 
          <li class="p-4 bg-white hover:bg-csun-red hover:text-white transition-all duration-300 ease-out"><a href="/profile">Profile</a></li>
          <li class="p-4 bg-white hover:bg-csun-red hover:text-white transition-all duration-300 ease-out"><a href="/logout">Sign Out</a></li>
        </ul>
      </li>
      <!-- If user NOT authed, show login --> 
      {% else %}
      <li><a href="/login">LOGIN</a></li>
      {% endif %}
    </ul>
  </nav>
</header>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} 

{% block head %}
<title>OnlyClubs</title>
{% endblock %} 

{% block body %} 
<div class="min-h-screen bg-gray-100 py-10">
  <div class="max-w-4xl mx-auto px-4">
    <h3 class="text-xl font-semibold mb-4">Recent Posts</h3>
      {% for post in posts %}
        {% include 'post.html' with context %}
      {% else %}
        <p>No posts found.</p>
      {% endfor %} 
    </h3>
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class="flex h-screen items-center justify-center bg-gray-100">
<div class="w-full max-w-sm mx-auto mt-10 mb-20 bg-white p-6 shadow-lg rounded">
  <h2 class="text-xl text-red-600 mb-8">Login</h2>
  <form action="/login" method="POST">
    <div class="mb-5">
      <label for="username" class="block mb-2 text-md font-medium text-gray-700">Username:</label>
      <input type="text" id="username" name="username" required class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-red-500 focus:border-red-500" />
    </div>
    <div class="mb-6">
      <label for="password" class="block mb-2 text-md font-medium text-gray-700">Password:</label>
      <input type="password" id="password" name="password" required class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-red-500 focus:border-red-500" />
    </div>
    <div class="flex justify-end">
      <button type="submit" class="px-5 py-2 border-2 border-black text-black transition-colors duration-200 transform bg-white hover:bg-red-600 hover:text-white rounded">Login</button>
    </div>
  </form>

  <p class="mt-6 text-center">If you don't have an account with us, Sign Up!</p>
  <div class="text-center">
    <a href="/register" role="button" class="inline-block px-5 py-2 mt-4 text-black border-2 border-red-600 rounded hover:bg-red-600 hover:text-white transition-colors duration-200 transform">Sign Up</a>
  </div>
</div>
</div>
{% endblock %}

app/templates/new-post.html
{% extends 'base.html' %}

{% block head %}
<title>New Post</title>
{% endblock %}

{% block body %}
<div class="min-h-screen bg-gray-100 flex items-center justify-center">
  <div class="max-w-lg w-full bg-white p-8 rounded-lg shadow">
    <h1 class="text-2xl font-bold mb-6">New Post</h1>
    <form action="/new-post" method="POST" class="space-y-4">
      <div>
        <label for="title" class="block text-sm font-medium text-gray-700">Title</label>
        <input type="text" name="title" id="title" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm" />
      </div>
      <div>
        <label for="content" class="block text-sm font-medium text-gray-700">Description</label>
        <textarea name="content" id="content" rows="10" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm" ></textarea>
      </div>
      <input type="submit" value="Add Post" class="w-full bg-csun-red hover:bg-red-700 text-white font-bold py-2 px-4 rounded cursor-pointer" />
    </form>
  </div>
</div>
{% endblock %}

app/templates/post.html
{% block post %}

<div class="bg-white p-6 rounded-lg shadow mb-4">
    <h2 class="text-2xl font-bold text-gray-800 mb-2">
      {{ post.title }}
      <span class="block h-1 bg-red-500 w-1/4 mt-2"></span>
    </h2>
    <p class="text-gray-600 mb-4">Posted by {{ post.user.full_name() }}</p>
    <p class="text-gray-700 mb-4">{{ post.content }}</p>
    <div class="flex space-x-4">
      <a href="/posts/{{ post.id }}" class="btn-primary">
        Read More
      </a>
      <a href="/events/join/{{ post.id }}" class="btn-primary">
        Join Event
      </a>
    </div>
</div>

{% endblock %}

app/templates/profile.html
{% extends 'base.html' %} 

{% block head %}
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/profile.css')}}"
/>
<title>User Profile</title>
{% endblock %}  

<!-- Profile Page -->


<div class="flex min-h-screen">
  {% block body %}
  <!-- Sidebar -->
  <div class="fixed 
              top-0 
              left-0 
              h-screen 
              w-16 
              m-0 
              py-3 
              flex 
              flex-col 
              bg-csun-red 
              text-white 
              text-center 
              shadow"
              >
    <!-- Sidebar Icons -->
    <a href="/">
      <i class="custom-sidebar-icon
              fa-solid 
              fa-home"></i>
    </a>
    <i class="custom-sidebar-icon
              fa-solid 
              fa-user"></i>
    <i class="custom-sidebar-icon
              fa-solid 
              fa-bullhorn"></i>
  </div>

  <!-- Main Profile Page Content -->
  <div class="mx-auto pl-16">
    <div class=" bg-gray-100">
      <div class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold leading-tight text-gray-900">
              {{user.full_name()}}
            </h1>
        </div>
    </div>
    <!-- Profile info -->
    <div class="max-w-4xl mx-auto py-6 sm:px-6 lg:px-8 mt-6">
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">
          <div class="px-4 py-5 sm:px-6 flex items-center">
              <i class="text-3xl rounded-full fa-solid fa-user"></i>
              <h3 class="text-lg leading-6 font-medium text-gray-900 ml-4">
                {{ user.full_name() }}
              </h3>
          </div>

          <div class="border-t border-gray-200">
              <dl>
                  <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                      <dt class="text-sm font-medium text-gray-500">
                          Email
                      </dt>
                      <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        {{ user.email }}
                      </dd>
                  </div>
                  <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                      <dt class="text-sm font-medium text-gray-500">
                          About
                      </dt>
                      <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      </dd>
                  </div>
                  
              </dl>
          </div>
      </div>
      
      <!-- Profile buttons -->
      <div class="mt-8 flex space-x-4">
          <a href="#" class="bg-csun-red hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
              Edit Profile
          </a>
    
          <a href="{{ url_for('auth.logout') }}" class="bg-csun-red hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
            Logout
        </a>
          
      </div>
    </div>
    
    <!-- Make a New Post -->
    <div class="max-w-2xl mx-auto py-6">
      <div class="bg-white p-6 mx-auto rounded-lg shadow-lg">
        <h2 class="text-2xl font-semibold mb-4">Post an Event</h2>
        <form action="/post-event" method="POST">
          <div class="mb-4">
            <label for="eventTitle" class="block text-sm font-medium text-gray-700">Event Title</label>
            <input type="text" name="eventTitle" id="eventTitle" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm" required>
          </div>
          <div class="mb-4">
            <label for="eventDescription" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea name="eventDescription" id="eventDescription" rows="4" class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm" required></textarea>
          </div>
          <div class="flex justify-between items-center">
            <button type="submit" class="inline-flex items-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-700 active:bg-red-900 focus:outline-none focus:border-red-900 focus:ring ring-red-300 disabled:opacity-25 transition ease-in-out duration-150">Post Event</button>
          </div>
        </form>
      </div>
    </div>
    

    <!-- User Posts -->
    <div class="min-h-screen bg-gray-100 py-10">
      <div class="max-w-4xl mx-auto px-4">
        <h3 class="text-xl font-semibold mb-4">Your Posts</h3>
        {% for post in current_user.posts %}
          {% include 'post.html' with context %}
        {% else %}
        <p class="text-gray-600">No posts found.</p>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endblock %}
</div>

app/templates/register.html
{% extends 'base.html' %}

{% block head %}
<title>Register</title>
{% endblock %}

{% block body %}
<div class="min-h-screen bg-gray-100 flex items-center justify-center">
  <div class="max-w-md w-full bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-2xl font-bold text-center mb-6">Register</h2>
    <form action="/register" method="POST" class="space-y-4">
      <div class="form-group">
        <label for="username" class="block text-sm font-medium text-gray-700">Username:</label>
        <input type="text" id="username" name="username" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" required />
      </div>
      <div class="form-group">
        <label for="email" class="block text-sm font-medium text-gray-700">Email:</label>
        <input type="text" id="email" name="email" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" required />
      </div>
      <div class="form-group">
        <label for="firstname" class="block text-sm font-medium text-gray-700">First name:</label>
        <input type="text" id="firstname" name="firstname" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" required />
      </div>
      <div class="form-group">
        <label for="lastname" class="block text-sm font-medium text-gray-700">Last name:</label>
        <input type="text" id="lastname" name="lastname" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" required />
      </div>
      <div class="form-group">
        <label for="password" class="block text-sm font-medium text-gray-700">Password:</label>
        <input type="password" id="password" name="password" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" required />
      </div>
      <div class="form-group">
        <label for="confirm-password" class="block text-sm font-medium text-gray-700">Confirm Password:</label>
        <input type="password" id="confirm-password" name="confirm-password" class="mt-1 block w-full p-2 border border-gray-300 rounded-md" required />
      </div>
      <div class="form-actions text-center">
        <button type="submit" class="px-4 py-2 bg-csun-red text-white font-bold rounded hover:bg-red-700">Register</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/update.html
{% extends 'base.html' %} 

{% block head %}
<title>Update Post</title>
{% endblock %} 

{% block body %}
<div class="content">
  <h1>Update Post</h1>

  <div class="form">
    <form action="/update/{{post.id}}" method="POST">
      <input type="text" name="content" id="content" value="{{post.content}}" />
      <input type="submit" value="Update" />
    </form>
  </div>
</div>
{% endblock %}